{
  "id": 4822612690,
  "sha": "adab22a85f59effe9ffb5e6401fbd788d0a80031",
  "name": "eggjs/egg",
  "target_url": "https://travis-ci.org/eggjs/egg/builds/365391978?utm_source=github_status&utm_medium=notification",
  "context": "continuous-integration/travis-ci/pr",
  "description": "The Travis CI build is in progress",
  "state": "pending",
  "commit": {
    "sha": "adab22a85f59effe9ffb5e6401fbd788d0a80031",
    "commit": {
      "author": {
        "name": "Haoliang Gao",
        "email": "sakura9515@gmail.com",
        "date": "2018-04-12T00:44:46Z"
      },
      "committer": {
        "name": "GitHub",
        "email": "noreply@github.com",
        "date": "2018-04-12T00:44:46Z"
      },
      "message": "Merge branch 'master' into docs-ts",
      "tree": {
        "sha": "cc33561b4ac2dab7a3d11a76bd97dbdc1cb757a1",
        "url": "https://api.github.com/repos/eggjs/egg/git/trees/cc33561b4ac2dab7a3d11a76bd97dbdc1cb757a1"
      },
      "url": "https://api.github.com/repos/eggjs/egg/git/commits/adab22a85f59effe9ffb5e6401fbd788d0a80031",
      "comment_count": 0,
      "verification": {
        "verified": true,
        "reason": "valid",
        "signature": "-----BEGIN PGP SIGNATURE-----\n\nwsBcBAABCAAQBQJazqv+CRBK7hj4Ov3rIwAAdHIIACqPJ+cyWGhMf2vUy85BX6MP\n6mi3G8MzXt2WMbH4sdsbAiwFfsqYDAk46Ca39+IWdDZORN1Py5z9mi556a4CKWwr\nAOT1pQlayvHfg3nPgz6JfIISYGZ2Hl/OlCfWCrPu1JxGhojpqSl82lnVSIt68Xs9\nfd2S/55MW8A5J4gq+3JdwZsddwiThnnckYVrlQdhAu/mdPyi7zPf0MWA1aJ0PRnY\nArGEud4Pheh1cgn4fY8+4RqFyS7BBnZ2kPwhC3IxSMksoS7Xn6eEaGWUONQDUIzh\nPOL8FmVPIzvxMIjrYSK723KNRXv/ZwnsB5jopJPpgnmetv/sFdNvLOgN+/4oTxY=\n=Haqa\n-----END PGP SIGNATURE-----\n",
        "payload": "tree cc33561b4ac2dab7a3d11a76bd97dbdc1cb757a1\nparent 41d034b550f8df3db18faa378c260cb54ef28729\nparent cd418f57a843b504dcac6d8c25b99026e1edf072\nauthor Haoliang Gao <sakura9515@gmail.com> 1523493886 +0800\ncommitter GitHub <noreply@github.com> 1523493886 +0800\n\nMerge branch 'master' into docs-ts"
      }
    },
    "url": "https://api.github.com/repos/eggjs/egg/commits/adab22a85f59effe9ffb5e6401fbd788d0a80031",
    "html_url": "https://github.com/eggjs/egg/commit/adab22a85f59effe9ffb5e6401fbd788d0a80031",
    "comments_url": "https://api.github.com/repos/eggjs/egg/commits/adab22a85f59effe9ffb5e6401fbd788d0a80031/comments",
    "author": {
      "login": "popomore",
      "id": 360661,
      "avatar_url": "https://avatars1.githubusercontent.com/u/360661?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/popomore",
      "html_url": "https://github.com/popomore",
      "followers_url": "https://api.github.com/users/popomore/followers",
      "following_url": "https://api.github.com/users/popomore/following{/other_user}",
      "gists_url": "https://api.github.com/users/popomore/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/popomore/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/popomore/subscriptions",
      "organizations_url": "https://api.github.com/users/popomore/orgs",
      "repos_url": "https://api.github.com/users/popomore/repos",
      "events_url": "https://api.github.com/users/popomore/events{/privacy}",
      "received_events_url": "https://api.github.com/users/popomore/received_events",
      "type": "User",
      "site_admin": false
    },
    "committer": {
      "login": "web-flow",
      "id": 19864447,
      "avatar_url": "https://avatars3.githubusercontent.com/u/19864447?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/web-flow",
      "html_url": "https://github.com/web-flow",
      "followers_url": "https://api.github.com/users/web-flow/followers",
      "following_url": "https://api.github.com/users/web-flow/following{/other_user}",
      "gists_url": "https://api.github.com/users/web-flow/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/web-flow/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/web-flow/subscriptions",
      "organizations_url": "https://api.github.com/users/web-flow/orgs",
      "repos_url": "https://api.github.com/users/web-flow/repos",
      "events_url": "https://api.github.com/users/web-flow/events{/privacy}",
      "received_events_url": "https://api.github.com/users/web-flow/received_events",
      "type": "User",
      "site_admin": false
    },
    "parents": [
      {
        "sha": "41d034b550f8df3db18faa378c260cb54ef28729",
        "url": "https://api.github.com/repos/eggjs/egg/commits/41d034b550f8df3db18faa378c260cb54ef28729",
        "html_url": "https://github.com/eggjs/egg/commit/41d034b550f8df3db18faa378c260cb54ef28729"
      },
      {
        "sha": "cd418f57a843b504dcac6d8c25b99026e1edf072",
        "url": "https://api.github.com/repos/eggjs/egg/commits/cd418f57a843b504dcac6d8c25b99026e1edf072",
        "html_url": "https://github.com/eggjs/egg/commit/cd418f57a843b504dcac6d8c25b99026e1edf072"
      }
    ]
  },
  "branches": [
    {
      "name": "docs-ts",
      "commit": {
        "sha": "adab22a85f59effe9ffb5e6401fbd788d0a80031",
        "url": "https://api.github.com/repos/eggjs/egg/commits/adab22a85f59effe9ffb5e6401fbd788d0a80031"
      }
    }
  ],
  "created_at": "2018-04-12T00:44:54Z",
  "updated_at": "2018-04-12T00:44:54Z",
  "repository": {
    "id": 61421257,
    "name": "egg",
    "full_name": "eggjs/egg",
    "owner": {
      "login": "eggjs",
      "id": 15833670,
      "avatar_url": "https://avatars1.githubusercontent.com/u/15833670?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/eggjs",
      "html_url": "https://github.com/eggjs",
      "followers_url": "https://api.github.com/users/eggjs/followers",
      "following_url": "https://api.github.com/users/eggjs/following{/other_user}",
      "gists_url": "https://api.github.com/users/eggjs/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/eggjs/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/eggjs/subscriptions",
      "organizations_url": "https://api.github.com/users/eggjs/orgs",
      "repos_url": "https://api.github.com/users/eggjs/repos",
      "events_url": "https://api.github.com/users/eggjs/events{/privacy}",
      "received_events_url": "https://api.github.com/users/eggjs/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/eggjs/egg",
    "description": "Born to build better enterprise frameworks and apps with Node.js & Koa",
    "fork": false,
    "url": "https://api.github.com/repos/eggjs/egg",
    "forks_url": "https://api.github.com/repos/eggjs/egg/forks",
    "keys_url": "https://api.github.com/repos/eggjs/egg/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/eggjs/egg/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/eggjs/egg/teams",
    "hooks_url": "https://api.github.com/repos/eggjs/egg/hooks",
    "issue_events_url": "https://api.github.com/repos/eggjs/egg/issues/events{/number}",
    "events_url": "https://api.github.com/repos/eggjs/egg/events",
    "assignees_url": "https://api.github.com/repos/eggjs/egg/assignees{/user}",
    "branches_url": "https://api.github.com/repos/eggjs/egg/branches{/branch}",
    "tags_url": "https://api.github.com/repos/eggjs/egg/tags",
    "blobs_url": "https://api.github.com/repos/eggjs/egg/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/eggjs/egg/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/eggjs/egg/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/eggjs/egg/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/eggjs/egg/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/eggjs/egg/languages",
    "stargazers_url": "https://api.github.com/repos/eggjs/egg/stargazers",
    "contributors_url": "https://api.github.com/repos/eggjs/egg/contributors",
    "subscribers_url": "https://api.github.com/repos/eggjs/egg/subscribers",
    "subscription_url": "https://api.github.com/repos/eggjs/egg/subscription",
    "commits_url": "https://api.github.com/repos/eggjs/egg/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/eggjs/egg/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/eggjs/egg/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/eggjs/egg/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/eggjs/egg/contents/{+path}",
    "compare_url": "https://api.github.com/repos/eggjs/egg/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/eggjs/egg/merges",
    "archive_url": "https://api.github.com/repos/eggjs/egg/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/eggjs/egg/downloads",
    "issues_url": "https://api.github.com/repos/eggjs/egg/issues{/number}",
    "pulls_url": "https://api.github.com/repos/eggjs/egg/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/eggjs/egg/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/eggjs/egg/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/eggjs/egg/labels{/name}",
    "releases_url": "https://api.github.com/repos/eggjs/egg/releases{/id}",
    "deployments_url": "https://api.github.com/repos/eggjs/egg/deployments",
    "created_at": "2016-06-18T06:53:23Z",
    "updated_at": "2018-04-12T00:44:09Z",
    "pushed_at": "2018-04-12T00:44:47Z",
    "git_url": "git://github.com/eggjs/egg.git",
    "ssh_url": "git@github.com:eggjs/egg.git",
    "clone_url": "https://github.com/eggjs/egg.git",
    "svn_url": "https://github.com/eggjs/egg",
    "homepage": "https://eggjs.org",
    "size": 42684,
    "stargazers_count": 7749,
    "watchers_count": 7749,
    "language": "JavaScript",
    "has_issues": true,
    "has_projects": false,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": true,
    "forks_count": 787,
    "mirror_url": null,
    "archived": false,
    "open_issues_count": 117,
    "license": {
      "key": "mit",
      "name": "MIT License",
      "spdx_id": "MIT",
      "url": "https://api.github.com/licenses/mit"
    },
    "forks": 787,
    "open_issues": 117,
    "watchers": 7749,
    "default_branch": "master"
  },
  "organization": {
    "login": "eggjs",
    "id": 15833670,
    "url": "https://api.github.com/orgs/eggjs",
    "repos_url": "https://api.github.com/orgs/eggjs/repos",
    "events_url": "https://api.github.com/orgs/eggjs/events",
    "hooks_url": "https://api.github.com/orgs/eggjs/hooks",
    "issues_url": "https://api.github.com/orgs/eggjs/issues",
    "members_url": "https://api.github.com/orgs/eggjs/members{/member}",
    "public_members_url": "https://api.github.com/orgs/eggjs/public_members{/member}",
    "avatar_url": "https://avatars1.githubusercontent.com/u/15833670?v=4",
    "description": "A web framework's framework for Node.js"
  },
  "sender": {
    "login": "killagu",
    "id": 6897780,
    "avatar_url": "https://avatars1.githubusercontent.com/u/6897780?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/killagu",
    "html_url": "https://github.com/killagu",
    "followers_url": "https://api.github.com/users/killagu/followers",
    "following_url": "https://api.github.com/users/killagu/following{/other_user}",
    "gists_url": "https://api.github.com/users/killagu/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/killagu/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/killagu/subscriptions",
    "organizations_url": "https://api.github.com/users/killagu/orgs",
    "repos_url": "https://api.github.com/users/killagu/repos",
    "events_url": "https://api.github.com/users/killagu/events{/privacy}",
    "received_events_url": "https://api.github.com/users/killagu/received_events",
    "type": "User",
    "site_admin": false
  }
}

{
  "id": 4820893159,
  "sha": "2fafb16b8810e41b86d15f51257c2a0531c78357",
  "name": "eggjs/egg",
  "target_url": "https://codecov.io/gh/eggjs/egg/commit/2fafb16b8810e41b86d15f51257c2a0531c78357",
  "context": "codecov/project",
  "description": "99.61% remains the same compared to ba708ca",
  "state": "success",
  "commit": {
    "sha": "2fafb16b8810e41b86d15f51257c2a0531c78357",
    "commit": {
      "author": {
        "name": "Suyi",
        "email": "thonatos@users.noreply.github.com",
        "date": "2018-04-11T16:20:17Z"
      },
      "committer": {
        "name": "Haoliang Gao",
        "email": "sakura9515@gmail.com",
        "date": "2018-04-11T16:20:17Z"
      },
      "message": "docs(socketio): update demo & solve problem on chrome (#2354)",
      "tree": {
        "sha": "adb34083b180476c4e7fe3d439bca4f6dc32410c",
        "url": "https://api.github.com/repos/eggjs/egg/git/trees/adb34083b180476c4e7fe3d439bca4f6dc32410c"
      },
      "url": "https://api.github.com/repos/eggjs/egg/git/commits/2fafb16b8810e41b86d15f51257c2a0531c78357",
      "comment_count": 0,
      "verification": {
        "verified": false,
        "reason": "unsigned",
        "signature": null,
        "payload": null
      }
    },
    "url": "https://api.github.com/repos/eggjs/egg/commits/2fafb16b8810e41b86d15f51257c2a0531c78357",
    "html_url": "https://github.com/eggjs/egg/commit/2fafb16b8810e41b86d15f51257c2a0531c78357",
    "comments_url": "https://api.github.com/repos/eggjs/egg/commits/2fafb16b8810e41b86d15f51257c2a0531c78357/comments",
    "author": {
      "login": "thonatos",
      "id": 958063,
      "avatar_url": "https://avatars2.githubusercontent.com/u/958063?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thonatos",
      "html_url": "https://github.com/thonatos",
      "followers_url": "https://api.github.com/users/thonatos/followers",
      "following_url": "https://api.github.com/users/thonatos/following{/other_user}",
      "gists_url": "https://api.github.com/users/thonatos/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thonatos/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thonatos/subscriptions",
      "organizations_url": "https://api.github.com/users/thonatos/orgs",
      "repos_url": "https://api.github.com/users/thonatos/repos",
      "events_url": "https://api.github.com/users/thonatos/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thonatos/received_events",
      "type": "User",
      "site_admin": false
    },
    "committer": {
      "login": "popomore",
      "id": 360661,
      "avatar_url": "https://avatars1.githubusercontent.com/u/360661?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/popomore",
      "html_url": "https://github.com/popomore",
      "followers_url": "https://api.github.com/users/popomore/followers",
      "following_url": "https://api.github.com/users/popomore/following{/other_user}",
      "gists_url": "https://api.github.com/users/popomore/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/popomore/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/popomore/subscriptions",
      "organizations_url": "https://api.github.com/users/popomore/orgs",
      "repos_url": "https://api.github.com/users/popomore/repos",
      "events_url": "https://api.github.com/users/popomore/events{/privacy}",
      "received_events_url": "https://api.github.com/users/popomore/received_events",
      "type": "User",
      "site_admin": false
    },
    "parents": [
      {
        "sha": "ba708ca4e911a345d2ee6aea5d4cf5845f93212b",
        "url": "https://api.github.com/repos/eggjs/egg/commits/ba708ca4e911a345d2ee6aea5d4cf5845f93212b",
        "html_url": "https://github.com/eggjs/egg/commit/ba708ca4e911a345d2ee6aea5d4cf5845f93212b"
      }
    ]
  },
  "branches": [
    {
      "name": "master",
      "commit": {
        "sha": "2fafb16b8810e41b86d15f51257c2a0531c78357",
        "url": "https://api.github.com/repos/eggjs/egg/commits/2fafb16b8810e41b86d15f51257c2a0531c78357"
      }
    },
    {
      "name": "docs-redirect",
      "commit": {
        "sha": "7bb97b9931306f0da1ebeea879d2e1b81b77190b",
        "url": "https://api.github.com/repos/eggjs/egg/commits/7bb97b9931306f0da1ebeea879d2e1b81b77190b"
      }
    }
  ],
  "created_at": "2018-04-11T17:52:24Z",
  "updated_at": "2018-04-11T17:52:24Z",
  "repository": {
    "id": 61421257,
    "name": "egg",
    "full_name": "eggjs/egg",
    "owner": {
      "login": "eggjs",
      "id": 15833670,
      "avatar_url": "https://avatars1.githubusercontent.com/u/15833670?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/eggjs",
      "html_url": "https://github.com/eggjs",
      "followers_url": "https://api.github.com/users/eggjs/followers",
      "following_url": "https://api.github.com/users/eggjs/following{/other_user}",
      "gists_url": "https://api.github.com/users/eggjs/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/eggjs/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/eggjs/subscriptions",
      "organizations_url": "https://api.github.com/users/eggjs/orgs",
      "repos_url": "https://api.github.com/users/eggjs/repos",
      "events_url": "https://api.github.com/users/eggjs/events{/privacy}",
      "received_events_url": "https://api.github.com/users/eggjs/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/eggjs/egg",
    "description": "Born to build better enterprise frameworks and apps with Node.js & Koa",
    "fork": false,
    "url": "https://api.github.com/repos/eggjs/egg",
    "forks_url": "https://api.github.com/repos/eggjs/egg/forks",
    "keys_url": "https://api.github.com/repos/eggjs/egg/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/eggjs/egg/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/eggjs/egg/teams",
    "hooks_url": "https://api.github.com/repos/eggjs/egg/hooks",
    "issue_events_url": "https://api.github.com/repos/eggjs/egg/issues/events{/number}",
    "events_url": "https://api.github.com/repos/eggjs/egg/events",
    "assignees_url": "https://api.github.com/repos/eggjs/egg/assignees{/user}",
    "branches_url": "https://api.github.com/repos/eggjs/egg/branches{/branch}",
    "tags_url": "https://api.github.com/repos/eggjs/egg/tags",
    "blobs_url": "https://api.github.com/repos/eggjs/egg/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/eggjs/egg/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/eggjs/egg/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/eggjs/egg/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/eggjs/egg/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/eggjs/egg/languages",
    "stargazers_url": "https://api.github.com/repos/eggjs/egg/stargazers",
    "contributors_url": "https://api.github.com/repos/eggjs/egg/contributors",
    "subscribers_url": "https://api.github.com/repos/eggjs/egg/subscribers",
    "subscription_url": "https://api.github.com/repos/eggjs/egg/subscription",
    "commits_url": "https://api.github.com/repos/eggjs/egg/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/eggjs/egg/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/eggjs/egg/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/eggjs/egg/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/eggjs/egg/contents/{+path}",
    "compare_url": "https://api.github.com/repos/eggjs/egg/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/eggjs/egg/merges",
    "archive_url": "https://api.github.com/repos/eggjs/egg/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/eggjs/egg/downloads",
    "issues_url": "https://api.github.com/repos/eggjs/egg/issues{/number}",
    "pulls_url": "https://api.github.com/repos/eggjs/egg/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/eggjs/egg/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/eggjs/egg/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/eggjs/egg/labels{/name}",
    "releases_url": "https://api.github.com/repos/eggjs/egg/releases{/id}",
    "deployments_url": "https://api.github.com/repos/eggjs/egg/deployments",
    "created_at": "2016-06-18T06:53:23Z",
    "updated_at": "2018-04-11T16:20:24Z",
    "pushed_at": "2018-04-11T16:30:49Z",
    "git_url": "git://github.com/eggjs/egg.git",
    "ssh_url": "git@github.com:eggjs/egg.git",
    "clone_url": "https://github.com/eggjs/egg.git",
    "svn_url": "https://github.com/eggjs/egg",
    "homepage": "https://eggjs.org",
    "size": 42684,
    "stargazers_count": 7749,
    "watchers_count": 7749,
    "language": "JavaScript",
    "has_issues": true,
    "has_projects": false,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": true,
    "forks_count": 787,
    "mirror_url": null,
    "archived": false,
    "open_issues_count": 118,
    "license": {
      "key": "mit",
      "name": "MIT License",
      "spdx_id": "MIT",
      "url": "https://api.github.com/licenses/mit"
    },
    "forks": 787,
    "open_issues": 118,
    "watchers": 7749,
    "default_branch": "master"
  },
  "organization": {
    "login": "eggjs",
    "id": 15833670,
    "url": "https://api.github.com/orgs/eggjs",
    "repos_url": "https://api.github.com/orgs/eggjs/repos",
    "events_url": "https://api.github.com/orgs/eggjs/events",
    "hooks_url": "https://api.github.com/orgs/eggjs/hooks",
    "issues_url": "https://api.github.com/orgs/eggjs/issues",
    "members_url": "https://api.github.com/orgs/eggjs/members{/member}",
    "public_members_url": "https://api.github.com/orgs/eggjs/public_members{/member}",
    "avatar_url": "https://avatars1.githubusercontent.com/u/15833670?v=4",
    "description": "A web framework's framework for Node.js"
  },
  "sender": {
    "login": "codecov[bot]",
    "id": 22429695,
    "avatar_url": "https://avatars2.githubusercontent.com/in/254?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/codecov%5Bbot%5D",
    "html_url": "https://github.com/apps/codecov",
    "followers_url": "https://api.github.com/users/codecov%5Bbot%5D/followers",
    "following_url": "https://api.github.com/users/codecov%5Bbot%5D/following{/other_user}",
    "gists_url": "https://api.github.com/users/codecov%5Bbot%5D/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/codecov%5Bbot%5D/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/codecov%5Bbot%5D/subscriptions",
    "organizations_url": "https://api.github.com/users/codecov%5Bbot%5D/orgs",
    "repos_url": "https://api.github.com/users/codecov%5Bbot%5D/repos",
    "events_url": "https://api.github.com/users/codecov%5Bbot%5D/events{/privacy}",
    "received_events_url": "https://api.github.com/users/codecov%5Bbot%5D/received_events",
    "type": "Bot",
    "site_admin": false
  }
}

{
  "action": "edited",
  "changes": {
    "body": {
      "from": "# [Codecov](https://codecov.io/gh/eggjs/egg/pull/2324?src=pr&el=h1) Report\n> Merging [#2324](https://codecov.io/gh/eggjs/egg/pull/2324?src=pr&el=desc) into [master](https://codecov.io/gh/eggjs/egg/commit/ba708ca4e911a345d2ee6aea5d4cf5845f93212b?src=pr&el=desc) will **not change** coverage.\n> The diff coverage is `n/a`.\n\n[![Impacted file tree graph](https://codecov.io/gh/eggjs/egg/pull/2324/graphs/tree.svg?token=2sKMCDNkcl&width=650&src=pr&height=150)](https://codecov.io/gh/eggjs/egg/pull/2324?src=pr&el=tree)\n\n```diff\n@@           Coverage Diff           @@\n##           master    #2324   +/-   ##\n=======================================\n  Coverage   99.61%   99.61%           \n=======================================\n  Files          29       29           \n  Lines         773      773           \n=======================================\n  Hits          770      770           \n  Misses          3        3\n```\n\n\n\n------\n\n[Continue to review full report at Codecov](https://codecov.io/gh/eggjs/egg/pull/2324?src=pr&el=continue).\n> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)\n> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`\n> Powered by [Codecov](https://codecov.io/gh/eggjs/egg/pull/2324?src=pr&el=footer). Last update [ba708ca...41d034b](https://codecov.io/gh/eggjs/egg/pull/2324?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).\n"
    }
  },
  "issue": {
    "url": "https://api.github.com/repos/eggjs/egg/issues/2324",
    "repository_url": "https://api.github.com/repos/eggjs/egg",
    "labels_url": "https://api.github.com/repos/eggjs/egg/issues/2324/labels{/name}",
    "comments_url": "https://api.github.com/repos/eggjs/egg/issues/2324/comments",
    "events_url": "https://api.github.com/repos/eggjs/egg/issues/2324/events",
    "html_url": "https://github.com/eggjs/egg/pull/2324",
    "id": 311853218,
    "number": 2324,
    "title": "docs: add TypeScript Guide",
    "user": {
      "login": "atian25",
      "id": 227713,
      "avatar_url": "https://avatars2.githubusercontent.com/u/227713?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/atian25",
      "html_url": "https://github.com/atian25",
      "followers_url": "https://api.github.com/users/atian25/followers",
      "following_url": "https://api.github.com/users/atian25/following{/other_user}",
      "gists_url": "https://api.github.com/users/atian25/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/atian25/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/atian25/subscriptions",
      "organizations_url": "https://api.github.com/users/atian25/orgs",
      "repos_url": "https://api.github.com/users/atian25/repos",
      "events_url": "https://api.github.com/users/atian25/events{/privacy}",
      "received_events_url": "https://api.github.com/users/atian25/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 3,
    "created_at": "2018-04-06T05:36:29Z",
    "updated_at": "2018-04-11T17:33:11Z",
    "closed_at": null,
    "author_association": "OWNER",
    "pull_request": {
      "url": "https://api.github.com/repos/eggjs/egg/pulls/2324",
      "html_url": "https://github.com/eggjs/egg/pull/2324",
      "diff_url": "https://github.com/eggjs/egg/pull/2324.diff",
      "patch_url": "https://github.com/eggjs/egg/pull/2324.patch"
    },
    "body": "<!--\r\nThank you for your pull request. Please review below requirements.\r\nBug fixes and new features should include tests and possibly benchmarks.\r\nContributors guide: https://github.com/eggjs/egg/blob/master/CONTRIBUTING.md\r\n\r\n感谢您贡献代码。请确认下列 checklist 的完成情况。\r\nBug 修复和新功能必须包含测试，必要时请附上性能测试。\r\nContributors guide: https://github.com/eggjs/egg/blob/master/CONTRIBUTING.md\r\n-->\r\n\r\n##### Checklist\r\n<!-- Remove items that do not apply. For completed items, change [ ] to [x]. -->\r\n\r\n- [ ] `npm test` passes\r\n- [ ] tests and/or benchmarks are included\r\n- [ ] documentation is changed or added\r\n- [ ] commit message follows commit guidelines\r\n\r\n##### Affected core subsystem(s)\r\n<!-- Provide affected core subsystem(s). -->\r\n\r\n\r\n##### Description of change\r\n<!-- Provide a description of the change below this comment. -->\r\n"
  },
  "comment": {
    "url": "https://api.github.com/repos/eggjs/egg/issues/comments/379242288",
    "html_url": "https://github.com/eggjs/egg/pull/2324#issuecomment-379242288",
    "issue_url": "https://api.github.com/repos/eggjs/egg/issues/2324",
    "id": 379242288,
    "user": {
      "login": "codecov[bot]",
      "id": 22429695,
      "avatar_url": "https://avatars2.githubusercontent.com/in/254?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/codecov%5Bbot%5D",
      "html_url": "https://github.com/apps/codecov",
      "followers_url": "https://api.github.com/users/codecov%5Bbot%5D/followers",
      "following_url": "https://api.github.com/users/codecov%5Bbot%5D/following{/other_user}",
      "gists_url": "https://api.github.com/users/codecov%5Bbot%5D/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/codecov%5Bbot%5D/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/codecov%5Bbot%5D/subscriptions",
      "organizations_url": "https://api.github.com/users/codecov%5Bbot%5D/orgs",
      "repos_url": "https://api.github.com/users/codecov%5Bbot%5D/repos",
      "events_url": "https://api.github.com/users/codecov%5Bbot%5D/events{/privacy}",
      "received_events_url": "https://api.github.com/users/codecov%5Bbot%5D/received_events",
      "type": "Bot",
      "site_admin": false
    },
    "created_at": "2018-04-06T12:46:11Z",
    "updated_at": "2018-04-11T17:33:11Z",
    "author_association": "NONE",
    "body": "# [Codecov](https://codecov.io/gh/eggjs/egg/pull/2324?src=pr&el=h1) Report\n> Merging [#2324](https://codecov.io/gh/eggjs/egg/pull/2324?src=pr&el=desc) into [master](https://codecov.io/gh/eggjs/egg/commit/ba708ca4e911a345d2ee6aea5d4cf5845f93212b?src=pr&el=desc) will **not change** coverage.\n> The diff coverage is `n/a`.\n\n[![Impacted file tree graph](https://codecov.io/gh/eggjs/egg/pull/2324/graphs/tree.svg?width=650&height=150&src=pr&token=2sKMCDNkcl)](https://codecov.io/gh/eggjs/egg/pull/2324?src=pr&el=tree)\n\n```diff\n@@           Coverage Diff           @@\n##           master    #2324   +/-   ##\n=======================================\n  Coverage   99.61%   99.61%           \n=======================================\n  Files          29       29           \n  Lines         773      773           \n=======================================\n  Hits          770      770           \n  Misses          3        3\n```\n\n\n\n------\n\n[Continue to review full report at Codecov](https://codecov.io/gh/eggjs/egg/pull/2324?src=pr&el=continue).\n> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)\n> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`\n> Powered by [Codecov](https://codecov.io/gh/eggjs/egg/pull/2324?src=pr&el=footer). Last update [ba708ca...41d034b](https://codecov.io/gh/eggjs/egg/pull/2324?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).\n"
  },
  "repository": {
    "id": 61421257,
    "name": "egg",
    "full_name": "eggjs/egg",
    "owner": {
      "login": "eggjs",
      "id": 15833670,
      "avatar_url": "https://avatars1.githubusercontent.com/u/15833670?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/eggjs",
      "html_url": "https://github.com/eggjs",
      "followers_url": "https://api.github.com/users/eggjs/followers",
      "following_url": "https://api.github.com/users/eggjs/following{/other_user}",
      "gists_url": "https://api.github.com/users/eggjs/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/eggjs/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/eggjs/subscriptions",
      "organizations_url": "https://api.github.com/users/eggjs/orgs",
      "repos_url": "https://api.github.com/users/eggjs/repos",
      "events_url": "https://api.github.com/users/eggjs/events{/privacy}",
      "received_events_url": "https://api.github.com/users/eggjs/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/eggjs/egg",
    "description": "Born to build better enterprise frameworks and apps with Node.js & Koa",
    "fork": false,
    "url": "https://api.github.com/repos/eggjs/egg",
    "forks_url": "https://api.github.com/repos/eggjs/egg/forks",
    "keys_url": "https://api.github.com/repos/eggjs/egg/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/eggjs/egg/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/eggjs/egg/teams",
    "hooks_url": "https://api.github.com/repos/eggjs/egg/hooks",
    "issue_events_url": "https://api.github.com/repos/eggjs/egg/issues/events{/number}",
    "events_url": "https://api.github.com/repos/eggjs/egg/events",
    "assignees_url": "https://api.github.com/repos/eggjs/egg/assignees{/user}",
    "branches_url": "https://api.github.com/repos/eggjs/egg/branches{/branch}",
    "tags_url": "https://api.github.com/repos/eggjs/egg/tags",
    "blobs_url": "https://api.github.com/repos/eggjs/egg/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/eggjs/egg/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/eggjs/egg/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/eggjs/egg/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/eggjs/egg/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/eggjs/egg/languages",
    "stargazers_url": "https://api.github.com/repos/eggjs/egg/stargazers",
    "contributors_url": "https://api.github.com/repos/eggjs/egg/contributors",
    "subscribers_url": "https://api.github.com/repos/eggjs/egg/subscribers",
    "subscription_url": "https://api.github.com/repos/eggjs/egg/subscription",
    "commits_url": "https://api.github.com/repos/eggjs/egg/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/eggjs/egg/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/eggjs/egg/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/eggjs/egg/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/eggjs/egg/contents/{+path}",
    "compare_url": "https://api.github.com/repos/eggjs/egg/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/eggjs/egg/merges",
    "archive_url": "https://api.github.com/repos/eggjs/egg/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/eggjs/egg/downloads",
    "issues_url": "https://api.github.com/repos/eggjs/egg/issues{/number}",
    "pulls_url": "https://api.github.com/repos/eggjs/egg/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/eggjs/egg/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/eggjs/egg/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/eggjs/egg/labels{/name}",
    "releases_url": "https://api.github.com/repos/eggjs/egg/releases{/id}",
    "deployments_url": "https://api.github.com/repos/eggjs/egg/deployments",
    "created_at": "2016-06-18T06:53:23Z",
    "updated_at": "2018-04-11T16:20:24Z",
    "pushed_at": "2018-04-11T16:30:49Z",
    "git_url": "git://github.com/eggjs/egg.git",
    "ssh_url": "git@github.com:eggjs/egg.git",
    "clone_url": "https://github.com/eggjs/egg.git",
    "svn_url": "https://github.com/eggjs/egg",
    "homepage": "https://eggjs.org",
    "size": 42684,
    "stargazers_count": 7749,
    "watchers_count": 7749,
    "language": "JavaScript",
    "has_issues": true,
    "has_projects": false,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": true,
    "forks_count": 787,
    "mirror_url": null,
    "archived": false,
    "open_issues_count": 118,
    "license": {
      "key": "mit",
      "name": "MIT License",
      "spdx_id": "MIT",
      "url": "https://api.github.com/licenses/mit"
    },
    "forks": 787,
    "open_issues": 118,
    "watchers": 7749,
    "default_branch": "master"
  },
  "organization": {
    "login": "eggjs",
    "id": 15833670,
    "url": "https://api.github.com/orgs/eggjs",
    "repos_url": "https://api.github.com/orgs/eggjs/repos",
    "events_url": "https://api.github.com/orgs/eggjs/events",
    "hooks_url": "https://api.github.com/orgs/eggjs/hooks",
    "issues_url": "https://api.github.com/orgs/eggjs/issues",
    "members_url": "https://api.github.com/orgs/eggjs/members{/member}",
    "public_members_url": "https://api.github.com/orgs/eggjs/public_members{/member}",
    "avatar_url": "https://avatars1.githubusercontent.com/u/15833670?v=4",
    "description": "A web framework's framework for Node.js"
  },
  "sender": {
    "login": "codecov[bot]",
    "id": 22429695,
    "avatar_url": "https://avatars2.githubusercontent.com/in/254?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/codecov%5Bbot%5D",
    "html_url": "https://github.com/apps/codecov",
    "followers_url": "https://api.github.com/users/codecov%5Bbot%5D/followers",
    "following_url": "https://api.github.com/users/codecov%5Bbot%5D/following{/other_user}",
    "gists_url": "https://api.github.com/users/codecov%5Bbot%5D/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/codecov%5Bbot%5D/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/codecov%5Bbot%5D/subscriptions",
    "organizations_url": "https://api.github.com/users/codecov%5Bbot%5D/orgs",
    "repos_url": "https://api.github.com/users/codecov%5Bbot%5D/repos",
    "events_url": "https://api.github.com/users/codecov%5Bbot%5D/events{/privacy}",
    "received_events_url": "https://api.github.com/users/codecov%5Bbot%5D/received_events",
    "type": "Bot",
    "site_admin": false
  }
}


{
  "action": "created",
  "issue": {
    "url": "https://api.github.com/repos/eggjs/egg/issues/2372",
    "repository_url": "https://api.github.com/repos/eggjs/egg",
    "labels_url": "https://api.github.com/repos/eggjs/egg/issues/2372/labels{/name}",
    "comments_url": "https://api.github.com/repos/eggjs/egg/issues/2372/comments",
    "events_url": "https://api.github.com/repos/eggjs/egg/issues/2372/events",
    "html_url": "https://github.com/eggjs/egg/issues/2372",
    "id": 313370356,
    "number": 2372,
    "title": "issue 机器人",
    "user": {
      "login": "popomore",
      "id": 360661,
      "avatar_url": "https://avatars1.githubusercontent.com/u/360661?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/popomore",
      "html_url": "https://github.com/popomore",
      "followers_url": "https://api.github.com/users/popomore/followers",
      "following_url": "https://api.github.com/users/popomore/following{/other_user}",
      "gists_url": "https://api.github.com/users/popomore/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/popomore/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/popomore/subscriptions",
      "organizations_url": "https://api.github.com/users/popomore/orgs",
      "repos_url": "https://api.github.com/users/popomore/repos",
      "events_url": "https://api.github.com/users/popomore/events{/privacy}",
      "received_events_url": "https://api.github.com/users/popomore/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 5,
    "created_at": "2018-04-11T15:17:10Z",
    "updated_at": "2018-04-11T17:19:17Z",
    "closed_at": null,
    "author_association": "OWNER",
    "body": "使用 https://github.com/eggjs/ant-bot 来帮助我们处理 issue，现在已经部署，但是需要根据我们的需求修改规则，可以在这个 issue 讨论下。\r\n\r\nant-design 的规则如下\r\n\r\nhttps://github.com/eggjs/ant-bot/tree/master/app/actions\r\n\r\n感谢 @yesmeck"
  },
  "comment": {
    "url": "https://api.github.com/repos/eggjs/egg/issues/comments/380529990",
    "html_url": "https://github.com/eggjs/egg/issues/2372#issuecomment-380529990",
    "issue_url": "https://api.github.com/repos/eggjs/egg/issues/2372",
    "id": 380529990,
    "user": {
      "login": "popomore",
      "id": 360661,
      "avatar_url": "https://avatars1.githubusercontent.com/u/360661?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/popomore",
      "html_url": "https://github.com/popomore",
      "followers_url": "https://api.github.com/users/popomore/followers",
      "following_url": "https://api.github.com/users/popomore/following{/other_user}",
      "gists_url": "https://api.github.com/users/popomore/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/popomore/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/popomore/subscriptions",
      "organizations_url": "https://api.github.com/users/popomore/orgs",
      "repos_url": "https://api.github.com/users/popomore/repos",
      "events_url": "https://api.github.com/users/popomore/events{/privacy}",
      "received_events_url": "https://api.github.com/users/popomore/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-04-11T17:19:17Z",
    "updated_at": "2018-04-11T17:19:17Z",
    "author_association": "OWNER",
    "body": "https://github.com/eggjs/egg/issues/2374 "
  },
  "repository": {
    "id": 61421257,
    "name": "egg",
    "full_name": "eggjs/egg",
    "owner": {
      "login": "eggjs",
      "id": 15833670,
      "avatar_url": "https://avatars1.githubusercontent.com/u/15833670?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/eggjs",
      "html_url": "https://github.com/eggjs",
      "followers_url": "https://api.github.com/users/eggjs/followers",
      "following_url": "https://api.github.com/users/eggjs/following{/other_user}",
      "gists_url": "https://api.github.com/users/eggjs/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/eggjs/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/eggjs/subscriptions",
      "organizations_url": "https://api.github.com/users/eggjs/orgs",
      "repos_url": "https://api.github.com/users/eggjs/repos",
      "events_url": "https://api.github.com/users/eggjs/events{/privacy}",
      "received_events_url": "https://api.github.com/users/eggjs/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/eggjs/egg",
    "description": "Born to build better enterprise frameworks and apps with Node.js & Koa",
    "fork": false,
    "url": "https://api.github.com/repos/eggjs/egg",
    "forks_url": "https://api.github.com/repos/eggjs/egg/forks",
    "keys_url": "https://api.github.com/repos/eggjs/egg/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/eggjs/egg/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/eggjs/egg/teams",
    "hooks_url": "https://api.github.com/repos/eggjs/egg/hooks",
    "issue_events_url": "https://api.github.com/repos/eggjs/egg/issues/events{/number}",
    "events_url": "https://api.github.com/repos/eggjs/egg/events",
    "assignees_url": "https://api.github.com/repos/eggjs/egg/assignees{/user}",
    "branches_url": "https://api.github.com/repos/eggjs/egg/branches{/branch}",
    "tags_url": "https://api.github.com/repos/eggjs/egg/tags",
    "blobs_url": "https://api.github.com/repos/eggjs/egg/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/eggjs/egg/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/eggjs/egg/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/eggjs/egg/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/eggjs/egg/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/eggjs/egg/languages",
    "stargazers_url": "https://api.github.com/repos/eggjs/egg/stargazers",
    "contributors_url": "https://api.github.com/repos/eggjs/egg/contributors",
    "subscribers_url": "https://api.github.com/repos/eggjs/egg/subscribers",
    "subscription_url": "https://api.github.com/repos/eggjs/egg/subscription",
    "commits_url": "https://api.github.com/repos/eggjs/egg/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/eggjs/egg/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/eggjs/egg/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/eggjs/egg/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/eggjs/egg/contents/{+path}",
    "compare_url": "https://api.github.com/repos/eggjs/egg/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/eggjs/egg/merges",
    "archive_url": "https://api.github.com/repos/eggjs/egg/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/eggjs/egg/downloads",
    "issues_url": "https://api.github.com/repos/eggjs/egg/issues{/number}",
    "pulls_url": "https://api.github.com/repos/eggjs/egg/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/eggjs/egg/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/eggjs/egg/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/eggjs/egg/labels{/name}",
    "releases_url": "https://api.github.com/repos/eggjs/egg/releases{/id}",
    "deployments_url": "https://api.github.com/repos/eggjs/egg/deployments",
    "created_at": "2016-06-18T06:53:23Z",
    "updated_at": "2018-04-11T16:20:24Z",
    "pushed_at": "2018-04-11T16:30:49Z",
    "git_url": "git://github.com/eggjs/egg.git",
    "ssh_url": "git@github.com:eggjs/egg.git",
    "clone_url": "https://github.com/eggjs/egg.git",
    "svn_url": "https://github.com/eggjs/egg",
    "homepage": "https://eggjs.org",
    "size": 42627,
    "stargazers_count": 7749,
    "watchers_count": 7749,
    "language": "JavaScript",
    "has_issues": true,
    "has_projects": false,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": true,
    "forks_count": 787,
    "mirror_url": null,
    "archived": false,
    "open_issues_count": 118,
    "license": {
      "key": "mit",
      "name": "MIT License",
      "spdx_id": "MIT",
      "url": "https://api.github.com/licenses/mit"
    },
    "forks": 787,
    "open_issues": 118,
    "watchers": 7749,
    "default_branch": "master"
  },
  "organization": {
    "login": "eggjs",
    "id": 15833670,
    "url": "https://api.github.com/orgs/eggjs",
    "repos_url": "https://api.github.com/orgs/eggjs/repos",
    "events_url": "https://api.github.com/orgs/eggjs/events",
    "hooks_url": "https://api.github.com/orgs/eggjs/hooks",
    "issues_url": "https://api.github.com/orgs/eggjs/issues",
    "members_url": "https://api.github.com/orgs/eggjs/members{/member}",
    "public_members_url": "https://api.github.com/orgs/eggjs/public_members{/member}",
    "avatar_url": "https://avatars1.githubusercontent.com/u/15833670?v=4",
    "description": "A web framework's framework for Node.js"
  },
  "sender": {
    "login": "popomore",
    "id": 360661,
    "avatar_url": "https://avatars1.githubusercontent.com/u/360661?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/popomore",
    "html_url": "https://github.com/popomore",
    "followers_url": "https://api.github.com/users/popomore/followers",
    "following_url": "https://api.github.com/users/popomore/following{/other_user}",
    "gists_url": "https://api.github.com/users/popomore/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/popomore/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/popomore/subscriptions",
    "organizations_url": "https://api.github.com/users/popomore/orgs",
    "repos_url": "https://api.github.com/users/popomore/repos",
    "events_url": "https://api.github.com/users/popomore/events{/privacy}",
    "received_events_url": "https://api.github.com/users/popomore/received_events",
    "type": "User",
    "site_admin": false
  }
}
